version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    registries:
      - npm-github
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "@navikt/*"
        update-types: []  # This ensures @navikt dependencies are not ignored
    groups:
      other-dependencies:
        patterns:
          - '*'
        update-types: ["version-update:semver-major"]
      aksel-dependencies:
        patterns:
          - '@navikt/aksel*'
          - '@navikt/ds*'
      arbeidsplassen-dependencies:
        patterns:
          - '@navikt/arbeidsplassen*'