name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/playwright ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      security-events: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@navikt'
    - name: Install dependencies
      run: npm ci
      env:
        NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
